### ISSUE TITLE
rmg-database build fails with KeyError: 'pydqed-1.0.1-py27_0.tar.bz2'

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-tests#20]
The following error occurs in a Travis CI build of a branch of RMG-database, after it seemingly successfully installed the `benchmark` conda environment.

```
SHA1: fd954f1528cf010e97fd56c4970601e571bc883d
Fetching package metadata: ....
Fetching package metadata: ....
src_prefix: '/home/travis/miniconda/envs/benchmark'
dst_prefix: '/home/travis/miniconda/envs/tested'
Packages: 67
Files: 0
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:
    https://github.com/conda/conda/issues
Include the output of the command 'conda info' in your report.
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/misc.py", line 246, in clone_env
    sorted_dists = r.dependency_sort(dists)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 729, in dependency_sort
    depends = lookup(value)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 724, in lookup
    return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 573, in ms_depends
    deps = [MatchSpec(d) for d in self.index[fn].get('depends', [])]
KeyError: 'pydqed-1.0.1-py27_0.tar.bz2'
```

**Comment by connie** [comment]
You are still using the latest miniconda.  Is there any way to get the old version back?

**Comment by rwest** [comment]
You can make it use whatever version you want from this list: http://repo.continuum.io/miniconda/

The benefit of always using the latest is that is what our users will use, and so we want our tests to fail if the latest fails.

**Comment by connie** [comment]
But our users don't use miniconda.  They use normal conda.

**Comment by nickvandewiele** [comment]
I indeed continued to use the latest conda version. 

The previous PR (#19) prevented the `update conda` command, which removed the previous error #18.

**Comment by nickvandewiele** [comment]
Also, this message only appears for builds triggered from RMG-database, not from RMG-Py.

**Comment by nickvandewiele** [comment]
The command that creates the error is:
`conda create --name tested --clone benchmark`

**Comment by nickvandewiele** [comment]
closed by https://github.com/ReactionMechanismGenerator/RMG-tests/pull/23
