### ISSUE TITLE
P-dep simulations fail with "AttributeError: 'PDepReaction' object has no attribute 'family'"

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-tests#21]
All the P-dep simulation cases (eg 5) run during the Travis CI build suffer from the same type of error:

```
Test model folder: /home/travis/build/ReactionMechanismGenerator/RMG-tests/testing/testmodel/eg5
Traceback (most recent call last):
  File "/home/travis/build/ReactionMechanismGenerator/code/tested/RMG-Py/scripts/checkModels.py", line 288, in <module>
    main()
  File "/home/travis/build/ReactionMechanismGenerator/code/tested/RMG-Py/scripts/checkModels.py", line 80, in main
    check(name, benchChemkin, benchSpeciesDict, testChemkin, testSpeciesDict)
  File "/home/travis/build/ReactionMechanismGenerator/code/tested/RMG-Py/scripts/checkModels.py", line 98, in check
    errorReactions = checkReactions(commonReactions, uniqueReactionsTest, uniqueReactionsOrig)
  File "/home/travis/build/ReactionMechanismGenerator/code/tested/RMG-Py/scripts/checkModels.py", line 186, in checkReactions
    [printReaction(rxn) for rxn in uniqueReactionsTest]
  File "/home/travis/build/ReactionMechanismGenerator/code/tested/RMG-Py/scripts/checkModels.py", line 263, in printReaction
    logger.error('rxn: {}\t\tfamily: {}'.format(rxn, rxn.family))
AttributeError: 'PDepReaction' object has no attribute 'family'
```

**Comment by nickvandewiele** [comment]
cf. https://github.com/ReactionMechanismGenerator/RMG-Py/pull/692
