### ISSUE TITLE
CI tests timeout due to Julia error

### ISSUE THREAD

**Issue by ChrisBNEU** [ReactionMechanismGenerator/RMG-tests#81]
The CI tests currently fail with the following error message:
```
Running benchmark job
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/benchmark/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 308, in main
    python(**vars(ns))
  File "/usr/share/miniconda/envs/benchmark/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 59, in python
    scope = runpy.run_path(script, run_name="__main__")
  File "/usr/share/miniconda/envs/benchmark/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/share/miniconda/envs/benchmark/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/share/miniconda/envs/benchmark/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/RMG-tests/RMG-tests/code/benchmark/RMG-Py/rmg.py", line 118, in <module>
    main()
  File "/home/runner/work/RMG-tests/RMG-tests/code/benchmark/RMG-Py/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/home/runner/work/RMG-tests/RMG-tests/code/benchmark/RMG-Py/rmgpy/rmg/main.py", line 707, in execute
    self.initialize(**kwargs)
  File "/home/runner/work/RMG-tests/RMG-tests/code/benchmark/RMG-Py/rmgpy/rmg/main.py", line 519, in initialize
    self.reaction_model.add_species_to_edge(spec)
  File "/home/runner/work/RMG-tests/RMG-tests/code/benchmark/RMG-Py/rmgpy/rmg/model.py", line 1146, in add_species_to_edge
    self.edge.phase_system.phases["Default"].add_species(spec)
  File "/home/runner/work/RMG-tests/RMG-tests/code/benchmark/RMG-Py/rmgpy/rmg/reactors.py", line 272, in add_species
    spec = to_rms(spc)
  File "/home/runner/work/RMG-tests/RMG-tests/code/benchmark/RMG-Py/rmgpy/rmg/reactors.py", line 516, in to_rms
    return rms.Species(obj.label, obj.index, "", "", "", thermo, atomnums, bondnum, diff, rad, obj.molecule[0].multiplicity-1, obj.molecular_weight.value_si)
RuntimeError: <PyCall.jlwrap (in a Julia function called from Python)
JULIA: MethodError: no method matching ReactionMechanismSimulator.Species(::String, ::Int64, ::String, ::String, ::String, ::ReactionMechanismSimulator.NASA{ReactionMechanismSimulator.EmptyThermoUncertainty}, ::Dict{Any, Any}, ::Int64, ::ReactionMechanismSimulator.StokesDiffusivity{Float64}, ::Float64, ::Int64, ::Float64)
Closest candidates are:
  ReactionMechanismSimulator.Species(::Any, ::Any, ::Any, ::Any, ::Any, ::T, ::Any, ::Any, ::N, ::Any, ::Any, ::Any, !Matched::N1, !Matched::N2) where {T<:ReactionMechanismSimulator.AbstractThermo, N<:ReactionMechanismSimulator.AbstractDiffusivity, N1<:ReactionMechanismSimulator.AbstractHenryLawConstant, N2<:ReactionMechanismSimulator.AbstractLiquidVolumetricMassTransferCoefficient} at /usr/share/miniconda/envs/benchmark/share/julia/site/packages/Parameters/MK0O4/src/Parameters.jl:526
Stacktrace:
  [1] invokelatest(::Any, ::Any, ::Vararg{Any, N} where N; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./essentials.jl:708
  [2] invokelatest(::Any, ::Any, ::Vararg{Any, N} where N)
    @ Base ./essentials.jl:706
  [3] _pyjlwrap_call(f::Type, args_::Ptr{PyCall.PyObject_struct}, kw_::Ptr{PyCall.PyObject_struct})
    @ PyCall /usr/share/miniconda/envs/benchmark/share/julia/site/packages/PyCall/7a7w0/src/callback.jl:28
  [4] pyjlwrap_call(self_::Ptr{PyCall.PyObject_struct}, args_::Ptr{PyCall.PyObject_struct}, kw_::Ptr{PyCall.PyObject_struct})
    @ PyCall /usr/share/miniconda/envs/benchmark/share/julia/site/packages/PyCall/7a7w0/src/callback.jl:44
  [5] macro expansion
    @ /usr/share/miniconda/envs/benchmark/share/julia/site/packages/PyCall/7a7w0/src/exception.jl:95 [inlined]
  [6] #107
    @ /usr/share/miniconda/envs/benchmark/share/julia/site/packages/PyCall/7a7w0/src/pyfncall.jl:43 [inlined]
  [7] disable_sigint
    @ ./c.jl:458 [inlined]
  [8] __pycall!
    @ /usr/share/miniconda/envs/benchmark/share/julia/site/packages/PyCall/7a7w0/src/pyfncall.jl:42 [inlined]
  [9] _pycall!(ret::PyObject, o::PyObject, args::Tuple{Vector{String}}, nargs::Int64, kw::Ptr{Nothing})
    @ PyCall /usr/share/miniconda/envs/benchmark/share/julia/site/packages/PyCall/7a7w0/src/pyfncall.jl:29
 [10] _pycall!
    @ /usr/share/miniconda/envs/benchmark/share/julia/site/packages/PyCall/7a7w0/src/pyfncall.jl:11 [inlined]
 [11] #_#114
    @ /usr/share/miniconda/envs/benchmark/share/julia/site/packages/PyCall/7a7w0/src/pyfncall.jl:86 [inlined]
 [12] (::PyObject)(args::Vector{String})
    @ PyCall /usr/share/miniconda/envs/benchmark/share/julia/site/packages/PyCall/7a7w0/src/pyfncall.jl:86
 [13] top-level scope
    @ none:4
 [14] eval
    @ ./boot.jl:360 [inlined]
 [15] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:261
 [16] _start()
    @ Base ./client.jl:485>
Benchmark job timed out
```

This occurs for every test case (aromatics, nitrogen, superminimal, etc.)

**Comment by JacksonBurns** [comment]
This was resolved in RMS PR [211](https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/pull/211)
